name: Deploy Demo
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout source code
        uses: actions/checkout@master

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install packages
        run: yarn

      - name: Create .env
        shell: bash
        run: |
          echo "REACT_APP_ETHERSCAN_API_KEY=${{ secrets.ETHERSCAN_API_KEY }}" >> .env.dev
          echo "REACT_APP_ETHERSCAN_API_KEY=${{ secrets.ETHERSCAN_API_KEY }}" >> .env.local
          echo "REACT_APP_ETHERSCAN_API_KEY=${{ secrets.ETHERSCAN_API_KEY }}" >> .env.prod

      - name: Build
        run: yarn run build:css && yarn run build:dev

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws s3 sync build s3://${{ secrets.S3_BUCKET }}
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_ID }}  --paths '/*'
