name: Deploy Demo
on:
  push:
    branches:
      - main-airstack

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:

      - name: Create .env
        shell: bash
        env:
          ENV_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: |
          echo API_KEY="$ENV_API_KEY" >> .env.dev

      - name: Checkout source code
        uses: actions/checkout@master

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install packages
        run: yarn

      - name: Build
        run: yarn run build:css && yarn run build:dev

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws s3 sync build s3://${{ secrets.S3_BUCKET_AIRSTACK }}
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_ID_AIRSTACK }}  --paths '/*'
